Repository 2024-LikeLionHackerton-MoodinG/MoodinG-BE, pull requests merged in 2024-07, with the labels that each got.

#3 feat: 이슈, PR 템플릿 추가
  .github/ISSUE_TEMPLATE/이슈-템플릿.md
  .github/PULL_REQUEST_TEMPLATE.md
Labels: 📄 문서, 🎸 기타 작업

#13 feat: 세션 생성 요청 API 구현
  build.gradle
  src/main/java/com/likelion/mooding/auth/presentation/AuthController.java
  src/test/java/com/likelion/mooding/auth/presentation/AuthControllerTest.java
Labels: 🛠️ 기능

#14 feat: 세션을 소유한 사용자에 대한 인증/인가 처리 구현
  src/main/java/com/likelion/mooding/auth/annotation/Auth.java
  src/main/java/com/likelion/mooding/auth/exception/SessionNotFoundException.java
  src/main/java/com/likelion/mooding/auth/exception/SessionTimeoutException.java
  src/main/java/com/likelion/mooding/auth/presentation/argumentresolver/GuestArgumentResolver.java
  src/main/java/com/likelion/mooding/auth/presentation/dto/Guest.java
  src/main/java/com/likelion/mooding/auth/presentation/interceptor/GuestInterceptor.java
  src/main/java/com/likelion/mooding/common/config/WebConfig.java
  src/main/java/com/likelion/mooding/common/exception/ExceptionResponse.java
  src/main/java/com/likelion/mooding/common/exception/GlobalExceptionHandler.java
Labels: 🛠️ 기능

#15 feat: 피드백 생성 요청 API 구현
  build.gradle
  src/main/java/com/likelion/mooding/auth/presentation/argumentresolver/GuestArgumentResolver.java
  src/main/java/com/likelion/mooding/auth/presentation/dto/Guest.java
  src/main/java/com/likelion/mooding/feedback/application/FeedbackChatCompletionService.java
  src/main/java/com/likelion/mooding/feedback/application/FeedbackService.java
  src/main/java/com/likelion/mooding/feedback/application/dto/FeedbackCreateResponse.java
  src/main/java/com/likelion/mooding/feedback/domain/Feedback.java
  src/main/java/com/likelion/mooding/feedback/domain/FeedbackRepository.java
  src/main/java/com/likelion/mooding/feedback/domain/FeedbackStatus.java
  src/main/java/com/likelion/mooding/feedback/presentation/FeedbackController.java
  src/main/java/com/likelion/mooding/feedback/presentation/dto/FeedbackCreateRequest.java
  src/main/java/com/likelion/mooding/infrastructure/openai/application/OpenAIFeedbackChatCompletionService.java
  src/main/java/com/likelion/mooding/infrastructure/openai/config/OpenAIConfig.java
  src/main/java/com/likelion/mooding/infrastructure/openai/constant/ChatCompletionRole.java
  src/main/java/com/likelion/mooding/infrastructure/openai/dto/ChatCompletionChoice.java
  src/main/java/com/likelion/mooding/infrastructure/openai/dto/ChatCompletionCreateRequest.java
  src/main/java/com/likelion/mooding/infrastructure/openai/dto/ChatCompletionCreateResponse.java
  src/main/java/com/likelion/mooding/infrastructure/openai/dto/ChatCompletionMessage.java
  src/main/resources/application.properties
  src/main/resources/application.yaml
  src/test/java/com/likelion/mooding/feedback/application/FeedbackServiceTest.java
  src/test/java/com/likelion/mooding/feedback/presentation/FeedbackControllerTest.java
Labels: 🛠️ 기능

#19 feat: 피드백 단건 조회 API 구현
  src/main/java/com/likelion/mooding/feedback/application/FeedbackService.java
  src/main/java/com/likelion/mooding/feedback/presentation/FeedbackController.java
  src/main/java/com/likelion/mooding/feedback/presentation/dto/FeedbackResultResponse.java
  src/test/java/com/likelion/mooding/e2e/E2EClient.java
  src/test/java/com/likelion/mooding/feedback/application/FeedbackServiceTest.java
  src/test/java/com/likelion/mooding/feedback/presentation/FeedbackControllerTest.java
Labels: 🛠️ 기능

#23 fix: 피드백 길이 변경
  src/main/java/com/likelion/mooding/feedback/domain/Feedback.java
Labels: 🪲 버그

#27 fix: 3000포트 요청에 대한 CORS 허용
  src/main/java/com/likelion/mooding/common/config/WebConfig.java
Labels: 🪲 버그

#32 fix: Cookie SameSite 및 Secure 설정 변경
  src/main/resources/application.yaml
Labels: 🪲 버그

#33 fix: CORS Origin 추가
  src/main/java/com/likelion/mooding/common/config/WebConfig.java
  src/main/resources/application.yaml
Labels: 🪲 버그

#35 fix: OPTION 요청에 대해 인터셉터가 true를 반환하도록 수정
  src/main/java/com/likelion/mooding/auth/presentation/interceptor/GuestInterceptor.java
Labels: 🪲 버그

#37 fix: CORS 설정 시, 응답 헤더 못 가져오는 문제 해결
  src/main/java/com/likelion/mooding/common/config/WebConfig.java
Labels: 🪲 버그
